[[parsers]]
l_file = "fathom/src/surface/lexer.l"
y_file = "fathom/src/surface/grammar.y"
extension = "fathom"
yacc_kind = {"Original" = "NoAction"}

[[tests]]
kind =  {"Dir" = "tests/fail/parse"}
pass = false

[[tests]]
kind = {"Dir" = "tests/succeed/**" }
pass = true
